# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ashley Howard | Front-end web developer
email: contact@ashley.how
formspree_full: mbjqojyp
formspree_enquiry: mzbyrbvb
description: >- # this means to ignore newlines until "baseurl:"
  A London-based web designer and developer, creating modern and mobile-friendly bespoke websites for small businesses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ashley.how" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: ahwebdev
github_username: ashley-howard
linkedin_username: ashlward
instagram_username: shley.how
codepen_username: shley
theme_colour: 35698A # the hex value

twitter:
  username: shleyhow
  card: summary

# Google Analytics
google_analytics: G-7CTXCXVG32

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

future: true # allow future dates in posts

collections:
  services:
  projects:
  case-studies:
    output: true
    permalink: /case-study/:title/
  posts:
    output: true
    permalink: /writing/:title/
  tags:
    output: true
    permalink: tags/:path/

defaults:
  - scope:
      path: "_tags"
    values:
      layout: "tags"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "case-studies"
    values:
      layout: "case-study"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      image: /assets-copy/images/apple-touch-icons/apple-touch-icon-180x180.png

# kramdown:
  # auto_ids: false ## why was this on?

exclude:
  - /assets-copy/scss/
  - README.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
