---
label: Service
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: link
  label: link
- type: text
  name: description
  label: description
- type: file
  name: image
  label: image
- type: text
  name: image_alt
  label: image_alt
- type: text
  name: accent
  label: accent
- type: text
  name: starting_at
  label: starting_at
